[tools]
bottom = "latest"
chezmoi = "latest"
go = "latest"
neovim = "latest"
ripgrep = "latest"
rust = "latest"
starship = "latest"
bat = "latest"
jq = "latest"
lazygit = "latest"
yazi = "latest"
zoxide = "latest"
age = "latest"
node = "20.18"
cheat = "latest"
kubectl = "latest"
k9s = "latest"
"vfox:version-fox/vfox-dotnet" = "latest"
