palette = "catppuccin_mocha"
format = """
$directory\
$git_branch\
$dotnet\
$time\
[ ](fg:teal)\
"""
add_newline = false

[directory]
style = "fg:surface0 bg:blue"
format = '[ $path ]($style)'
disabled = false
use_os_path_sep = false
truncate_to_repo = true

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:surface0 bg:maroon"
format = '[ $symbol $branch ]($style)'
disabled = false

[golang]
symbol = ""
style = "fg:text bg:#007d9c"
format = '[ $symbol ($version) ]($style)'
disabled = false

[nodejs]
symbol = ""
style = "fg:surface0 bg:green"
format = '[ $symbol ($version) ]($style)'
disabled = false

[rust]
symbol = ""
style = "fg:text bg:#a72145"
format = '[ $symbol ($version) ]($style)'
disabled = false

[dotnet]
symbol = "󰪮"
style = "fg:surface0 bg:sapphire"
format = '[ $symbol ($version) ]($style)'
disabled = false

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:surface0 bg:teal"
format = '[  $time ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
